---
- hosts: SolidfireNodes
  gather_facts: no
  connection: local
  tasks:
  - name: Collect facts
    na_elementsw_cluster_info_custom:
      hostname: "{{ SF_HOSTNAME }}"
      username: "{{ SF_USERNAME }}"
      password: "{{ SF_PASSWORD }}"
    register: testout
    ignore_errors: yes
    
  - debug: var=testout
