---
- hosts: SOLIDFIRE01
  connection: local
  tasks:
  - name: Create Volume
    na_elementsw_volume:
      hostname: "{{ inventory_hostname }}"
      username: "{{ SF_USERNAME }}"
      password: "{{ SF_PASSWORD }}"
      state: present
      name: "{{ volname }}"
      qos: {minIOPS: 1000, maxIOPS: 20000, burstIOPS: 50000}
      account_id: 1
      enable512e: True
      size: "{{ volsize }}"
      size_unit: gb
    register: testout
  - name: Write debug
    debug:
      msg: "{{ testout }}"
  - pause:
      seconds: 2
      
- hosts: SOLIDFIRE01
  connection: local
  tasks:
  - name: Present Volume
    na_elementsw_access_group:
      hostname: "{{ inventory_hostname }}"
      username: "{{ SF_USERNAME }}"
      password: "{{ SF_PASSWORD }}"
      src_access_group_id: "{{ accessgroupname }}"
      state: present
      volumes: ["{{ volname }}"]
