---
- hosts: SolidfireNodes
  gather_facts: no
  connection: local
  tasks:
  - name: Create Volume
    na_elementsw_volume:
      hostname: VCSA
      username: "{{ SF_USERNAME }}"
      password: "{{ SF_PASSWORD }}"
      state: present
      name: "{{ volname }}"
      qos: {minIOPS: 1000, maxIOPS: 20000, burstIOPS: 50000}
      account_id: 1
      enable512e: True
      size: "{{ volsize }}"
      size_unit: gb
    register: testout
  - set_fact: 
      NAA: "{{ 'naa.' + testout.msg }}"
    
  - name: Write debug
    debug:
      msg: "{{ NAA }}"
      
- hosts: SolidfireNodes
  gather_facts: no
  connection: local
  tasks:
  - name: Present Volume
    na_elementsw_access_group:
      hostname: "{{ inventory_hostname }}"
      username: "{{ SF_USERNAME }}"
      password: "{{ SF_PASSWORD }}"
      src_access_group_id: "{{ accessgroupname }}"
      account_id: 1
      state: present
      volumes: ["{{ volname }}"]

- hosts: ESXiHosts
  gather_facts: no
  connection: local
  tasks:
  - name: Rescan Host Storage
    vmware_host_scanhba:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ VCC_USERNAME }}"
      password: "{{ VCC_PASSWORD }}"
      cluster_name: "{{ accessgroupname }}"
      validate_certs: false

- hosts: ESXiHosts[0]
  gather_facts: no
  connection: local
  tasks:
  - name: Write NAA testing
    debug:
      msg: "{{ hostvars[groups['SolidfireNodes'][0]]['NAA'] }}"
  - name: Create datastore
    vmware_host_datastore:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ VCC_USERNAME }}"
      password: "{{ VCC_PASSWORD }}"
      esxi_hostname: "{{ inventory_hostname }}"
      datastore_name: "{{ volname }}"
      datastore_type: vmfs
      vmfs_device_name: "{{ hostvars[groups['SolidfireNodes'][0]]['NAA'] }}"
      vmfs_version: 6
      state: present
      validate_certs: false
