---
- hosts: SOLIDFIRE01
  connection: local
  vars:
    accountid: 1
  tasks:
  - name: Create Volume
    na_elementsw_volume:
      hostname: "{{ inventory_hostname }}"
      username: "{{ SF_USERNAME }}"
      password: "{{ SF_PASSWORD }}"
      state: present
      name: "{{ volname }}"
      qos: {minIOPS: 1000, maxIOPS: 20000, burstIOPS: 50000}
      account_id: "{{ accountid }}"
      enable512e: True
      size: "{{ volsize }}"
      size_unit: gb
  - pause:
      seconds: 10
      
- hosts: SOLIDFIRE01
  connection: local
  vars:
    accountid: 1
  tasks:
  - name: Present Volume
    na_elementsw_access_group:
      hostname: "{{ inventory_hostname }}"
      username: "{{ SF_USERNAME }}"
      password: "{{ SF_PASSWORD }}"
      src_access_group_id: "{{ accessgroupname }}"
      state: present
      volumes: "{{ volname }}"
