---
- name: Solidfire Delete Volume
  hosts: localhost
  connection: local
  vars:
    volname: default
    accountid: 1
    
  tasks:
  - name: Delete Volume
    na_elementsw_volume:
      hostname: "{{ inventory_hostname }}"
      username: "{{ SF_USERNAME }}"
      password: "{{ SF_PASSWORD }}"
      state: absent
      name: "{{ volname }}"
      account_id: "{{ accountid }}"
