---
- hosts: SolidfireNodes
  connection: local
  tasks:
  - name: Present Volume
    na_elementsw_access_group:
      hostname: "{{ inventory_hostname }}"
      username: "{{ SF_USERNAME }}"
      password: "{{ SF_PASSWORD }}"
      src_access_group_id: "{{ accessgroupname }}"
      account_id: 1
      state: present
      volumes: ["{{ volname }}"]
