---
- hosts: SolidfireNodes
  gather_facts: no
  connection: local
  tasks:
  - name: update servicenow request
    snow_record:
      username: "{{ snow_user }}"
      password: "{{ snow_password }}"
      instance: "{{ snow_instance }}"
      state: present
      table: u_chrissfvolrequest
      number: "{{ snow_request }}"
      data:
        work_notes: "Started playbook - snow-sfcreate"
    ignore_errors: yes
    
  - name: Create Volume
    na_elementsw_volume:
      hostname: "{{ sfclustername }}"
      username: "{{ SF_USERNAME }}"
      password: "{{ SF_PASSWORD }}"
      state: present
      name: "{{ sfvolname }}"
      qos: {minIOPS: 1000, maxIOPS: 20000, burstIOPS: 50000}
      account_id: 1
      enable512e: True
      size: "{{ sfvolsize }}"
      size_unit: gb
    register: testout
  - set_fact: 
      NAA: "{{ 'naa.' + testout.msg }}"
    
  - name: update servicenow request
    snow_record:
      username: "{{ snow_user }}"
      password: "{{ snow_password }}"
      instance: "{{ snow_instance }}"
      state: present
      table: u_chrissfvolrequest
      number: "{{ snow_request }}"
      data:
        work_notes: "Volume created. Completed playbook - snow-sfcreate"
        state: 3
    ignore_errors: yes
