---
- hosts: SolidfireNodes
  gather_facts: no
  connection: local
  tasks:
  - name: update servicenow request
    snow_record:
      username: "{{ snow_user }}"
      password: "{{ snow_password }}"
      instance: "{{ snow_instance }}"
      state: present
      table: u_chrissfvolrequest
      number: "{{ snow_request }}"
      data:
        work_notes: "Started playbook - snow-sfclusterinfo"
    ignore_errors: yes  
  - name: Collect facts
    na_elementsw_cluster_info_custom:
      hostname: "{{ sfclustername }}"
      username: "{{ SF_USERNAME }}"
      password: "{{ SF_PASSWORD }}"
    register: testout
    ignore_errors: yes
  - name: debug cluster capacity
    set_fact: 
      dataresult: "{{ testout.cluster_capacity | from_json }}"
  - debug: var=dataresult.active_block_space

  - name: update servicenow request
    snow_record:
      username: "{{ snow_user }}"
      password: "{{ snow_password }}"
      instance: "{{ snow_instance }}"
      state: present
      table: u_chrissfvolrequest
      number: "{{ snow_request }}"
      data:
        work_notes: "Prechecks run. Completed playbook - snow-sfclusterinfo"
        u_sfmaxblockcapacity: "{{ (dataresult.max_used_space / 1000000000) | round(2,'common') }}"
        u_sfusedspace: "{{ (dataresult.used_space / 1000000000) | round(2,'common')  }}"
        u_sfavailablespace: "{{ ((dataresult.max_used_space - dataresult.used_space) / 1000000000) | round(2,'common')  }}"
    ignore_errors: yes  
