---
- hosts: SolidfireNodes
  gather_facts: no
  connection: local
  tasks:
  - name: Collect facts
    na_elementsw_cluster_info_custom:
      hostname: "{{ sfclustername }}"
      username: "{{ SF_USERNAME }}"
      password: "{{ SF_PASSWORD }}"
    register: testout
    ignore_errors: yes
  - name: debug cluster capacity
    set_fact: 
      dataresult: "{{ testout.cluster_capacity | from_json }}"
  - debug: var=dataresult.active_block_space

  - name: update servicenow request
    snow_record:
      username: "{{ snow_user }}"
      password: "{{ snow_password }}"
      instance: "{{ snow_instance }}"
      state: present
      table: u_chrissfvolrequest
      number: "{{ snow_request }}"
      data:
        work_notes: "Prechecks run"
        u_sfmaxblockcapacity: "{{ dataresult.max_used_space }}"
        u_sfusedspace: "{{ dataresult.used_space }}"
        u_sfavailablespace: "{{ dataresult.max_used_space - dataresult.used_space }}"
    ignore_errors: yes  
